site_name: My Personal blog
nav:
    - Home: ../
    - "Blog de SAS":
        - "Introducci칩n a SAS": sas/intro_sas.md
    - "Blog de R":
        - "Introducci칩n a R": r/intro_r.md
    - "Blog de Python":
        - "Introducci칩n a Python": python/intro_python.md
        - "Python nivel b치sico": python/basico.md
    - About: about.md
theme:
    name: material
repo_url: https://github.com/FranciscoAriel/FranciscoAriel.github.io
edit_uri: blob/master/docs/
site_url: https://FranciscoAriel.github.io/site/
markdown_extensions:
    - smarty
    - admonition
    - codehilite:
        linenums: true
    - toc:
        permalink: True
